### ISSUE TITLE
Response object fields should match glossary

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#103]
Our response object fields are out of date. The new design has each object share all fields except applications which have two extra fields.

To keep our code more DRY and set the stage for an eventual data model change, I think we should use a mixin to define shared fields and apply them to multiple tables.

**Comment by rmarow** [comment]
https://github.com/nsidc/usaon-vta-docs/blob/main/glossary.md#fields
