### ISSUE TITLE
Survey status

### ISSUE THREAD

**Issue by rmarow** [nsidc/usaon-vta-survey#113]
Survey page should show status.
What do we want our status options to be? - glossary has WIP, Published, Closed, Archived right now.
Should only Admins be able to edit status?

**Comment by MattF-NSIDC** [comment]
It's not clear to me yet how status works. I think we need to have a team discussion on this. It would be nice if we could have a quick and dirty flowchart representation of status transitions so we are all on the same page.

> Should only Admins be able to edit status?

I'm imagining statuses would transition naturally as the result of different user events, for example a respondent "completing" their response would maybe update the survey's status to "responded", and then an admin would have to "publish" after that. A bit nebulous to me. Apologies if this is in the glossary already. My time is a mess today!
