### ISSUE TITLE
Display partial chart preview while filling out survey

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#14]
Display preview of Sankey diagram while entering survey response. E.g. when editing a observing system -> data product relationship, render all data products and observing systems.

> :memo: Would be nice to have the ability to toggle either displaying the full chart or displaying only the elements currently being edited. Would also be nice to be able to navigate the survey by clicking chart elements.

**Comment by rmarow** [comment]
Preview takes filter function as argument.

**Comment by rmarow** [comment]
@MattF-NSIDC  I think this is good to be closed - it is intertwined a bit with #146 but the parts related to the previews is complete :) Photos attached below.

![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/a487829a-266e-48a3-bec7-a0ed399f64b5)
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/16708f73-b668-42ad-b0c6-a74e9bbdfe6a)
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/4ba76407-d0d7-45fb-a722-a50f08511d7b)

**Comment by MattF-NSIDC** [comment]
If the work is still on a branch and not merged in, I don't think we should close it yet. What about linking it to the PR so it autocloses?

**Comment by rmarow** [comment]
Great call. Will do that.
