### ISSUE TITLE
Create analyst role and diagram view page

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#146]
* New role: Analyst
* New page: View survey diagram, viewable by any role.

Browsing, sorting, and filtering for another ticket

**Comment by rmarow** [comment]
Current state:

![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/d760959b-4a02-4723-80e6-a14edd9cdbb3)

**Comment by rmarow** [comment]
ToDo:

- figure out incorporating performance and criticality rating
- look at lines crossing
- im sure there is more.

**Comment by MattF-NSIDC** [comment]
Few more ideas from looking at the legacy app. I don't think any of these should necessarily be in this ticket :)

- [ ] Tooltips / mousovers (is that what you meant by your first bullet?)
- [ ] Color scheme(s)
    - [ ] by node type
    - [ ] by performance rating (the current app says "by value")
    - [ ] Legend(s)

**Comment by rmarow** [comment]
Limited analyst so they can view response, but make no edits to it
