### ISSUE TITLE
set up SSO with github or google

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#28]

**Comment by rmarow** [comment]
Currently going with Google using flask-dance (https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html#code)

**Comment by rmarow** [comment]
Created a branch https://github.com/nsidc/usaon-vta-survey/tree/setup_sso

**Comment by rmarow** [comment]
If someone got a new email or job would we be able to consolidate?

**Comment by MattF-NSIDC** [comment]
>If someone got a new email or job would we be able to consolidate?

We chatted about this and decided this shouldn't be a concern until much farther down the line. For now, let them create a new account.
