### ISSUE TITLE
Enable users to be designated as admins

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#29]
Enable a registered user to be designated as an admin

**Comment by rmarow** [comment]
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/d5335deb-e048-42c4-8777-bd5ebba4b706)

**Comment by MattF-NSIDC** [comment]
We decided on this morning's call that for now all users will be designated as "admin" by default upon registration.

**Comment by rmarow** [comment]
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/0915098f-ae20-45ac-9c80-cbfa1e4ed101)

**Comment by rmarow** [comment]
https://github.com/nsidc/usaon-vta-survey/pull/48

**Comment by rmarow** [comment]
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/d6192cd6-f0da-4bbf-bba8-d3d4f703274c)
