### ISSUE TITLE
Admin survey listing page

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#31]
Admins can see all created surveys, their title, their created and updated dates, creator, and their status on a listing page.

- [ ] Ensure all new features comply with [user interface design doc](https://docs.google.com/presentation/d/1TW5oS7dcM9w7Jze4Wey_TozGvwvB0IHjF4bRx8TU-O8/edit#slide=id.g1c127e95d9a_0_56)

**Comment by rmarow** [comment]
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/a714d2b6-27bd-424a-ae94-ea87ac9cd979)

current state

**Comment by MattF-NSIDC** [comment]
Looks like we may need to add some new survey fields to meet the requirements of this ticket.

**Comment by rmarow** [comment]
view when i survey has never been responded to or edited
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/98c3a137-251a-460f-b748-c04a9b1a04a6)

**Comment by MattF-NSIDC** [comment]
Maybe we just need to add the `title` field?

**Comment by rmarow** [comment]
![Image](https://github.com/nsidc/usaon-vta-survey/assets/103532760/292639ec-6513-4aa1-a993-883793affb0b)

View when there has been a response

**Comment by rmarow** [comment]
good call. Adding title field now

**Comment by rmarow** [comment]
NOTE: currently you can see survey list before being logged in

**Comment by MattF-NSIDC** [comment]
Ah, that's probably something we should cover in this ticket. Great point. Only show the survey list page to users who have the admin role (which means by extension the user must be logged in). What do you think?
