### ISSUE TITLE
Enable users to logout

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#46]
Following:

https://flask-login.readthedocs.io/en/latest/#login-example

Looks like a piece of cake to just add a new route...

```python
@app.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(somewhere)
```

...but we may need to also do oauth things with flask-dance to tell Google that the user is logged out of our app. 

Based on the flask-dance docs, I think we don't need to do anything with Google.
https://flask-dance.readthedocs.io/en/latest/logout.html#log-out-local-account

The whole section on logging out is a good read.

**Comment by rmarow** [comment]
<img width="368" alt="Screen Shot 2023-07-25 at 5 51 35 PM" src="https://github.com/nsidc/usaon-vta-survey/assets/103532760/71de9cae-680a-41eb-8f6f-09fc9b331c47">
