### ISSUE TITLE
Set up production proxy rules

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#78]
Request system admins to create a new Apache proxy rule to expose our app to the public internet. It should probably be under the usaon hostname we already host. (What is that URL?)

**Comment by rmarow** [comment]
Ticket open here: https://nsidc.org/jira/browse/SAS-15552

**Comment by rmarow** [comment]
NOTE: The URL may change as USAON is looking at some updated names from VTA.

**Comment by rmarow** [comment]
https://qa.usaon.org/apps/value-tree-analysis/ QA URL with proxy setup

**Comment by rmarow** [comment]
Related to #87

**Comment by rmarow** [comment]
QA link doesn't work after login because of the links being different.  

- `x-forwarded-prefix` header should be provided by the proxy rule ask anthony for that in Jira ticket.
- we need to update the app to expect and handle the `x-forwarded-prefix` header.
