### ISSUE TITLE
Automate adding issues to this project board

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#8]

**Comment by rmarow** [comment]
@MattF-NSIDC is this issue still relevant?

**Comment by MattF-NSIDC** [comment]
Auto-adding is supported, but only for one repo per project. We would need to pay to support >1 repo auto-adding issues to a project :sob: You'd think GitHub would have more to offer paying customers so they didn't feel they need to paywall simple quality-of-life features like this!

This repo is set up to auto-add its issues to our project, but we need to be mindful of creating new issues in the docs repo or db repo, because they won't be auto-added.

That need is expressed here: https://github.com/nsidc/.github/issues/16 , so I think we can close this issue.
