### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#80]
- [x] Release MVP
- [x] Create blue VM
- [x] Request ops Blue/Green swap
- [x] Request ops Garrison deployment of MVP release

**Comment by rmarow** [comment]
https://nsidc.org/jira/browse/PCT-3131 https://nsidc.org/jira/browse/PCT-3133

**Comment by rmarow** [comment]
Deployed, but Marin ran in to issues with the environment variables. Next time if there are manual steps may want to note that secrets are held in vault.

**Comment by rmarow** [comment]
@MattF-NSIDC yes
