### ISSUE TITLE
Change release workflow to be triggered on tag push instead of GH Release

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#85]
It's easy to forget release steps (bumpversion, CHANGELOG, and more) when releasing from the GUI. Releasing from CLI by pushing a tag should make it a bit easier to remember the CLI-specific steps like version bumping.

**Comment by rmarow** [comment]
Changed on this commit: 4ac8f786fcb274dabcab7365ff8d3fbd01cd5bc2
