### ISSUE TITLE
Populate SBA reference data

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#89]
Our reference data is incomplete for SBAs. Flesh it out based on (TODO: Link)

**Comment by rmarow** [comment]
https://www.arcticobserving.org/images/pdf/misc/STPI-SAON-International-Arctic-Observations-Framework-Report-2017.pdf

**Comment by rmarow** [comment]
@hazelshapiro could you add the SBA spreadsheet link here for visibility

**Comment by hazelshapiro** [comment]
Societal Benefit Areas spreadsheet for the STPI-SAON International Arctic Observations Framework Report (2017)
https://docs.google.com/spreadsheets/d/1pTvFVg-7YsJLqJ81YsMXwustwN28x-Jfkce9Znx0bHM/edit#gid=0
