### ISSUE TITLE
Response page should show survey title

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#94]

**Comment by rmarow** [comment]
<img width="524" alt="Screen Shot 2023-08-18 at 3 14 19 PM" src="https://github.com/nsidc/usaon-vta-survey/assets/103532760/bbe9f229-5ecb-4be4-a9e0-557ce1ad07ba">
Survey title is on this page but should be made bigger and maybe should say `survey title` 
<img width="933" alt="Screen Shot 2023-08-18 at 3 20 16 PM" src="https://github.com/nsidc/usaon-vta-survey/assets/103532760/dca83df5-7eed-4ab0-8514-d83480e39bb7">
Need to add title here too!

**Comment by MattF-NSIDC** [comment]
Yeah, I think we should make the UUID really small and the title really big!

**Comment by MattF-NSIDC** [comment]
In the "Response" section, it might be nice to say "View response started by <respondent>" instead of "View response"

**Comment by rmarow** [comment]
@MattF-NSIDC how will we handle that when there is more than one respondent?

**Comment by MattF-NSIDC** [comment]
Good catch; our data model does not support that yet... we would need to add an [associative entity](https://en.wikipedia.org/wiki/Associative_entity) between Users and Responses.

We would also need to think more about concurrency. If two people attempt to update a record at the same time, how do we handle it? For example, do our DB queries only update changed fields, or do they naively update the entire record? We could look in the postgres logs. Should our app keep track of "who is looking at what page" so that we can warn users when they might collide?

Let's keep thinking about it!
